// =================================================================================
// This is auto-generated by GoFrame CLI tool only once. Fill this file as you wish.
// =================================================================================

package kube

import (
	"gf-admin/api/kube"
	logic "gf-admin/internal/logic/kube"
)

type ControllerV1 struct{}

func NewV1() kube.IKubeV1 {
	logic.SetDefaultCluster()
	return &ControllerV1{}
}
